<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" Version="3.5.215"/>
    <PackageReference Include="MemoryPack.Core" Version="1.21.4" />
    <PackageReference Include="Stride.Core.Mathematics" Version="4.2.1.2485" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mir3.Shared\Mir3.Shared.csproj" />
  </ItemGroup>

</Project>
